const GIT_REPOS_WITH_WATCHERS = "GIT_REPOS_WITH_WATCHERS";
const ALL_COMMITS_GIT = "COMMITS_GIT";
const GET_COMMITS_USER = "GET_COMMITS_USER";
const SAVE_INPUT_TEXT = "SAVE_INPUT_TEXT";
const EXPANDED = "EXPANDED";
const DELETE_COMMITS_USER = "DELETE_COMMITS_USER";
const RESULT_SEARCH = "RESULT_SEARCH";
const HIDDEN_ELEMENT = "HIDDEN_ELEMENT";

export {
  GIT_REPOS_WITH_WATCHERS,
  DELETE_COMMITS_USER,
  ALL_COMMITS_GIT,
  GET_COMMITS_USER,
  SAVE_INPUT_TEXT,
  EXPANDED,
  RESULT_SEARCH,
  HIDDEN_ELEMENT,
};
